### ISSUE TITLE
Atualizar README.md

### ISSUE THREAD

**Issue by leonofre** [leonofre/ENozes#1]
## Adicionar informações sobre o jogo. ##
 - [x] Descrição do Projeto;
 - [x] Nome dos colaboradores;
 - [x] Descrição curta sobre a história do jogo;
 - [x] Funcionalidades básicas;

**Comment by bigode98** [comment]
Atualizando as informações:

Descrição do Projeto; (Assesement baseado no desenvolvimento de um jogo em plataforma no estilo de I wanna be the guy)
Nome dos colaboradores;(Meirillene, Jessica, Carlos, Leonardo, Gabriel, Wallace, Pedro, Saul, Vinicius, )
Descrição curta sobre a história do jogo;
Funcionalidades básicas;

**Comment by bigode98** [comment]
Descrição do Projeto - 
Jogo em plataforma no estilo de "I wanna be the guy".

Nome dos colaboradores - Gabriel, Meirillene, Jessica, Leonardo, Carlos, Vinicius, Saul, Wallace, Pedro, Ramulo.

Descrição curta sobre a história do jogo - 
Com a destruição da floresta, nosso herói nada normal decide salvar-la, tendo recompensa como uma 
adorável companhia e seu sossego  outra vez.

Funcionalidades básicas -
.Andar para direita
.Andar para esquerda
.Pular
.Atirar nozes

**Comment by leonofre** [comment]
@bigode98 novamente você cometeu o mesmo erro da outra issue, você deveria ter inserido esse conteúdo formatado com markdown no arquivo README.md e não no comentário, corrija e quando tiver terminado me chame para avaliar antes de fechar a issue
