### ISSUE TITLE
Tela inicial (Layout)

### ISSUE THREAD

**Issue by leonofre** [leonofre/ENozes#3]
- [x] Criação do layout da tela inicial do jogo

**Comment by leonofre** [comment]
![Layout1](https://github.com/leonofre/ProjetoBlocoAndroid/blob/master/imagens/menu1.jpg?raw=true)
![Layout2](https://github.com/leonofre/ProjetoBlocoAndroid/blob/master/imagens/menu2.jpg?raw=true)
Fiz 2 exemplos de layout para a tela inicial, votem na que acharem melhor.

**Comment by viniciusnuunes** [comment]
1

**Comment by carlosvfernandes** [comment]
1
