### ISSUE TITLE
Logo do time e do jogo

### ISSUE THREAD

**Issue by leonofre** [leonofre/ENozes#8]
### Criar layout para a logo do time (ControlF13) ###
 - [x] Criar 2 exemplos
 - [x] Enviar no comentário da issue para que haja uma votação
### Criar layout para a logo do jogo (É nozes) ###
 - [x] Criar 2 exemplos
 - [x] Enviar no comentário da issue para que haja uma votação

### Para finalizar ###
 - [x] Criar uma branch partindo da master
 - [x] colocar as imagens nessa branch
 - [x] Abrir um Pull Request

**Comment by pschlude** [comment]
![22690088_1507319456024801_1574041346_o](https://user-images.githubusercontent.com/31660695/31839242-0122188e-b5bf-11e7-8c51-a99d9952d70c.jpg)
![22690270_1507319526024794_515091425_o](https://user-images.githubusercontent.com/31660695/31839243-013eec20-b5bf-11e7-995a-2314fac241f1.jpg)
![22711806_1507319356024811_493944090_o](https://user-images.githubusercontent.com/31660695/31839244-0161eea0-b5bf-11e7-8c0f-f74abefbc61a.jpg)
![22768266_1507319602691453_597132676_o](https://user-images.githubusercontent.com/31660695/31839245-017d7a12-b5bf-11e7-9b2f-a7b714a07b8f.jpg)

sao todos prototipos com ma qualidade, mas acho que da pra entender a ideia de cada um, aberto a sugestoes

**Comment by leonofre** [comment]
Bom, vamos lá, com relação a logo do jogo, eu preferi a segunda  opção, mas acho q seria uma boa colocar um fundo, talvez redondo, atrás dela: algo no estilo dessa imagem, mas puxando para o nosso tema, talvez no lugar do carimbo, podíamos fazer algo como um troco de árvore, e o nome do jogo em relevo
![image](https://user-images.githubusercontent.com/19397230/31846196-0cc71540-b5e7-11e7-9135-58239d68b5f0.png)
O control f13 eu também gostei mais da segunda imagem, se você conseguir dar um efeito de tecla de computador acho q vai ficar bom, mas também poderíamos colocar umas teclas em volta e dar um destaque só no Control + F13, talvez com uma cor diferente ou brilho maior.
Acho que é isso, aguardando o restante da galera comentar.

**Comment by jessiicasantos** [comment]
As logos ficaram bonitinhas *-*

**Comment by jessiicasantos** [comment]
Mas a logo da última imagem tá parecendo uma pimenta kkkkkk

**Comment by carlosvfernandes** [comment]
Achei melhor a segunda imagem pra logo do time e a segunda pra logo do jogo, só precisa dar uma melhorada nessa noz porque ta muito fina.

**Comment by jessiicasantos** [comment]
Eu achei que as duas primeiras logos ficaram ótimas
A primeira imagem podia botar o quadrado de fundo preto e deixar nos botões as cores de um teclado normal
Ouuu
Põe só o segundo ctrl f13 mesmo, só que talvez não sobressaia tanto na tela do jogo. Então voto na 1.
E eu preferi a logo do Énozis arredondada.

**Comment by viniciusnuunes** [comment]
2ª logo énozes
3ª logo do f13 que parece um botão comum
